# Generated by Django 4.2.7 on 2024-03-19 18:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_balance'),
    ]

    operations = [
        migrations.AlterField(
            model_name='balance',
            name='currency',
            field=models.CharField(max_length=10),
        ),
    ]
