# Generated by Django 4.2.7 on 2024-03-19 19:10

import budget_tracker.accounts.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_alter_balance_currency'),
    ]

    operations = [
        migrations.AlterField(
            model_name='budgettrackeruser',
            name='first_name',
            field=models.CharField(max_length=150, validators=[budget_tracker.accounts.validators.validate_name_contains_only_letters]),
        ),
        migrations.AlterField(
            model_name='budgettrackeruser',
            name='last_name',
            field=models.CharField(max_length=150, validators=[budget_tracker.accounts.validators.validate_name_contains_only_letters]),
        ),
    ]
