# Generated by Django 4.2.7 on 2024-03-23 19:09

import budget_tracker.accounts.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_alter_budgettrackeruser_first_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to=budget_tracker.accounts.models.user_directory_path),
        ),
    ]
