# Generated by Django 4.2.7 on 2024-04-17 18:30

import budget_tracker.accounts.validators
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_remove_userprofile_photo_profilephoto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='budgettrackeruser',
            name='first_name',
            field=models.CharField(max_length=50, validators=[budget_tracker.accounts.validators.validate_name_contains_only_letters, budget_tracker.accounts.validators.validate_name_starts_with_capital_letter, django.core.validators.MinLengthValidator(3, message='A name must contain at least 3 letters')]),
        ),
        migrations.AlterField(
            model_name='budgettrackeruser',
            name='last_name',
            field=models.CharField(max_length=50, validators=[budget_tracker.accounts.validators.validate_name_contains_only_letters, budget_tracker.accounts.validators.validate_name_starts_with_capital_letter, django.core.validators.MinLengthValidator(3, message='A name must contain at least 3 letters')]),
        ),
    ]
