# Generated by Django 4.2.7 on 2024-04-18 18:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_alter_budgettrackeruser_first_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='currency',
            name='currency',
            field=models.CharField(choices=[('€ EUR', '€ EUR'), ('$ USD', '$ USD'), ('£ GBP', '£ GBP'), ('лв BGN', 'лв BGN')], default='€ EUR'),
        ),
    ]
