# Generated by Django 4.2.7 on 2024-11-01 17:25

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0004_alter_expense_amount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expense',
            name='description',
            field=models.CharField(default='Groceries', max_length=60, validators=[django.core.validators.MinLengthValidator(5, message='Expense description must contain at least 5 characters!')]),
            preserve_default=False,
        ),
    ]
