# Generated by Django 4.2.7 on 2023-12-01 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('income', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='income',
            name='currency',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
