# Generated by Django 4.2.7 on 2024-03-07 09:37

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('income', '0004_alter_income_amount'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='income',
            name='submitted_on',
        ),
        migrations.AddField(
            model_name='income',
            name='date',
            field=models.DateField(blank=True, default=datetime.date.today),
        ),
    ]
