# Generated by Django 4.2.7 on 2024-03-12 10:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('income', '0006_income_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='income',
            name='amount',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
    ]
