# Generated by Django 4.2.7 on 2024-04-18 13:47

import budget_tracker.income.validators
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('income', '0007_alter_income_amount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='income',
            name='amount',
            field=models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(5, message='Minimum amount must be greater than 5')]),
        ),
        migrations.AlterField(
            model_name='income',
            name='source',
            field=models.CharField(max_length=30, validators=[django.core.validators.MinLengthValidator(4, message='Income source must contain at least 4 characters'), budget_tracker.income.validators.validate_income_source_contains_only_letters]),
        ),
    ]
