# Generated by Django 4.2.7 on 2024-04-23 13:17

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('income', '0008_alter_income_amount_alter_income_source'),
    ]

    operations = [
        migrations.AlterField(
            model_name='income',
            name='amount',
            field=models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(5, message='Minimum amount must be at least 5')]),
        ),
        migrations.AlterField(
            model_name='income',
            name='currency',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='income',
            name='type',
            field=models.CharField(choices=[('Earned Income', 'Earned Income'), ('Passive Income', 'Passive Income'), ('Portfolio Income', 'Portfolio Income')], max_length=25),
        ),
    ]
